version: '3.7'

volumes:
  vhost:
  challange:

networks:
  proxy_proxy:
    external: true
  vault:
    driver: bridge

services:
  vault:
    image: vault
    networks:
      - proxy_proxy
      - vault
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
    deploy:
      restart_policy:
        condition: on-failure
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
    environment:
      VIRTUAL_HOST: "firstvault.janga.la"
      LETSENCRYPT_HOST: "firstvault.janga.la"
      VIRTUAL_PORT: "8200"
