version: '3.7'

volumes:
  vhost:

networks:
  proxy_proxy:
    external: true
  vault:
    driver: overlay

services:
  vault:
    image: vault
    networks:
    - proxy_proxy
    - vault
    volumes:
    - ./volumes/logs:/vault/logs
    - ./volumes/file:/vault/file
    - ./volumes/config:/vault/config
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      VIRTUAL_HOST: "52.51.166.228:8200"
      LETSENCRYPT_HOST: "52.51.166.228:8200"
